openmrs/openmrs-module-uicommons

scss/src/main/resources/sass/reference/fragments/_form-navigator-ui.scss

Please see fix for multi-line labels such as the address field.

RA-490 fixing address label

---

api/src/main/resources/messages.properties
omod/src/main/webapp/resources/scripts/navigator/validators.js

Adding PhoneField validator. Use "cssClasses": ["phone"] to a field

RA-593 - Allow common non-numeric characters in phone numbers

---

pom.xml
tools/src/main/resources/eclipse/OpenMRSFormatter.xml

Add missing maven formatter plugin for OpenMRS modules

Add missing maven formatter plugin for OpenMRS modules

---

omod/src/main/webapp/resources/scripts/angular-common.js
omod/src/main/webapp/resources/scripts/services/privilegeService.js
omod/src/main/webapp/resources/scripts/services/roleService.js

New branch off new rebase master

RA-806 Manage Roles

---

omod/src/main/webapp/fragments/infoAndErrorMessage.gsp

Reverts openmrs/openmrs-module-uicommons#29

Revert "Fix xss issue in infoMessage popups on patient dashboard"

---

omod/src/main/webapp/fragments/field/multipleInputDate.gsp

Issue: https://issues.openmrs.org/browse/UICM-82

UICM-82 Add label error in multipleInputDate

---

omod/src/main/webapp/resources/scripts/services/visitTypeService.js

Added Angular Visit Type service implementation 
Ticket : https://issues.openmrs.org/browse/UICM-85

UICM-85 Added Angular visitTypeService

---

omod/src/main/webapp/fragments/field/text.gsp
omod/src/main/webapp/fragments/field/textarea.gsp
omod/src/main/webapp/resources/scripts/navigator/navigator.js
scss/src/main/resources/sass/reference/fragments/_buttons.scss
scss/src/main/resources/sass/reference/fragments/_login.scss

This PR contains changes for the GSoC Project Bootstrap as a foundation for Ref App UI project.
It contains the following changes up to now
1) Adding the responsiveness to login page and replacing the html components with bootstrap components.
2) Making text field responsiveness.
3) Making text area field responsiveness.
This PR will have more commit's when the project is going forward.
Ticket ID :- RA-1952

RA-1592 : Boostrap as a foundation for Reference Application UI Project.

---

omod/src/main/webapp/fragments/field/text.gsp
omod/src/main/webapp/fragments/field/textarea.gsp
scss/src/main/resources/sass/reference/fragments/_buttons.scss
scss/src/main/resources/sass/reference/fragments/_login.scss

Reverts openmrs/openmrs-module-uicommons#52

Revert "RA-1592 : Boostrap as a foundation for Reference Application UI Project."

---

omod/src/main/webapp/fragments/field/datetimepicker.gsp

This PR contains changes for the GSoC Project Bootstrap as a foundation for Ref App UI project.
It contains the following changes up to now
1.fix jquery conflict.
This PR will have more commit's when the project is going forward.
Ticket ID :- https://issues.openmrs.org/browse/RA-1592

RA-1592 : Boostrap as a foundation for Reference Application UI Project. 

---

omod/src/main/webapp/fragments/field/datetimepicker.gsp

…he expected datatype if provided as strings
Ticket : https://issues.openmrs.org/browse/UICM-90

UICM-90: datetimepicker able to parse dates provided as string

---

omod/src/main/webapp/fragments/field/datetimepicker.gsp

Ticket: https://issues.openmrs.org/browse/UICM-90

UICM-90: datetimepicker parses String params into appropriate data type.

---

omod/src/main/webapp/fragments/field/datetimepicker.gsp

Tested with passing all-new parameters and without any parameters.
ISSUE Link: https://issues.openmrs.org/browse/UICM-92

UICM-92: Parameterise formats and minuteStep in datepicker.gsp

---

omod/src/main/webapp/fragments/field/datetimepicker.gsp

Ticket : https://issues.openmrs.org/browse/RA-1691

RA-1691: Date Time widget/fragment fallback format to use 'en'.

---

omod/src/main/webapp/fragments/field/multipleInputDate.gsp

Ticket : https://issues.openmrs.org/browse/UICM-94

UICM-94: multipleInputDate.gsp widget to have explicit </div> closure.

---

omod/src/main/webapp/fragments/field/multipleInputDate.gsp
omod/src/main/webapp/fragments/field/personAddress.gsp

Related ticket: https://issues.openmrs.org/browse/RA-1773
Related PR with changes in registrationapp module - https://github.com/openmrs/openmrs-module-registrationapp/pull/78

RA-1773: Corrected inconsistencies with 'require' label

---

api/src/main/resources/messages.properties
omod/src/main/webapp/fragments/field/dropDown.gsp
omod/src/main/webapp/fragments/validationMessages.gsp
omod/src/main/webapp/resources/scripts/navigator/navigatorModels.js
omod/src/main/webapp/resources/scripts/navigator/validators.js

Add autocomplete option for select widgets

---

omod/src/main/webapp/resources/scripts/navigator/navigatorModels.js

Hi,
This fix is an extended version of EMPT61 andI guess this also fixed EMPT 171.  Kindly review the same.
Also, here's the link for relevant details for EMPT61 :-  https://github.com/openmrs/openmrs-module-registrationapp/pull/110
For EMPT171 :-
Go to Register a Patient
--
Enter <SCRIPT SRC=http://xss.rocks/xss.js></SCRIPT> in all the input fields in the form if client side validator allows it
Press Confirm from the left menu.
Link to ticket
RA-1875 (https://issues.openmrs.org/browse/RA-1875)
@isears

Made changes to Fix EMPT 61 and EMPT171.

---

omod/src/main/webapp/resources/scripts/navigator/navigatorModels.js

Reverts openmrs/openmrs-module-uicommons#89

Revert "Made changes to Fix EMPT 61 and EMPT171."

---

omod/src/main/webapp/resources/scripts/directives/coded-or-free-text-answer.js

Hey @ibacher  @mogoodrich  @gracepotma @dkayiwa   could you please review this
**TICKET NAME**
https://issues.openmrs.org/browse/UICM-88

UICM-88: Incorrect instance of quotation mark in coded-or-free-text-answer.js file

---

omod/src/main/webapp/resources/scripts/navigator/navigatorHandlers.js

Issue: https://issues.openmrs.org/browse/UICM-101

UICM-101 Add a null check to questionsHandler.selectedQuestion().field

---

omod/src/main/webapp/resources/scripts/filters/serverDate.js

These allow locale-specific formatting.

Add angular filters for formatting dates

---

.github/workflows/main.yml
api/pom.xml
omod/pom.xml
pom.xml
scss/pom.xml

Ticket: https://openmrs.atlassian.net/browse/UICM-106
2.x branch: https://github.com/openmrs/openmrs-module-uicommons/tree/2.x

UICM-106: Update to OpenMRS platform 2.7.3 and Support Java 21
